become_override: false
ocp_username: opentlc-mgr
silent: false
guid: test

# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

ocp4_workload_connectivity_link_openshift_gitops_operator_channel: latest
ocp4_workload_connectivity_link_openshift_gitops_operator_automatic_install_plan_approval: true
ocp4_workload_connectivity_link_openshift_gitops_operator_starting_csv: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_name: openshift-gitops-operator
ocp4_workload_connectivity_link_openshift_gitops_operator_namespace: openshift-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog: redhat-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_use_catalog_snapshot: false
ocp4_workload_connectivity_link_openshift_gitops_operator_catalogsource_name: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_catalogsource_namespace: openshift-operators
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog_snapshot_image: ""
ocp4_workload_connectivity_link_openshift_gitops_operator_catalog_snapshot_image_tag: ""

ocp4_workload_connectivity_link_openshift_gitops_setup_cluster_admin: true

ocp4_workload_connectivity_link_openshift_gitops_update_route_tls: true

ocp4_workload_connectivity_link_openshift_gitops_update_resources: true

# ApplicationSet Controller
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_update: false
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_requests_memory: 512Mi
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_limits_cpu: "2"
ocp4_workload_connectivity_link_openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
ocp4_workload_connectivity_link_openshift_gitops_controller_update: false
ocp4_workload_connectivity_link_openshift_gitops_controller_requests_cpu: 512m
ocp4_workload_connectivity_link_openshift_gitops_controller_requests_memory: 1Gi
ocp4_workload_connectivity_link_openshift_gitops_controller_limits_cpu: "4"
ocp4_workload_connectivity_link_openshift_gitops_controller_limits_memory: 4Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
ocp4_workload_connectivity_link_openshift_gitops_controller_app_sync: 3m

ocp4_workload_connectivity_link_openshift_gitops_controller_remove_memory_limits: false

# Redis
ocp4_workload_connectivity_link_openshift_gitops_redis_update: false
ocp4_workload_connectivity_link_openshift_gitops_redis_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_redis_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_redis_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
ocp4_workload_connectivity_link_openshift_gitops_repo_update: false
ocp4_workload_connectivity_link_openshift_gitops_repo_requests_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_repo_requests_memory: 512Mi
ocp4_workload_connectivity_link_openshift_gitops_repo_limits_cpu: "2"
ocp4_workload_connectivity_link_openshift_gitops_repo_limits_memory: 2Gi

# DEX
ocp4_workload_connectivity_link_openshift_gitops_dex_update: false
ocp4_workload_connectivity_link_openshift_gitops_dex_requests_cpu: 125m
ocp4_workload_connectivity_link_openshift_gitops_dex_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_dex_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_dex_limits_memory: 256Mi

# Server
ocp4_workload_connectivity_link_openshift_gitops_server_update: false
ocp4_workload_connectivity_link_openshift_gitops_server_requests_cpu: 250m
ocp4_workload_connectivity_link_openshift_gitops_server_requests_memory: 128Mi
ocp4_workload_connectivity_link_openshift_gitops_server_limits_cpu: 500m
ocp4_workload_connectivity_link_openshift_gitops_server_limits_memory: 256Mi

ocp4_workload_connectivity_link_openshift_gitops_resource_customizations: |
  operators.coreos.com/Subscription:
    health.lua: |
      health_status = {}
      if obj.status ~= nil then
        if obj.status.conditions ~= nil then
          numDegraded = 0
          numPending = 0
          msg = ""
          for i, condition in pairs(obj.status.conditions) do
            msg = msg .. i .. ": " .. condition.type .. " | " .. condition.status .. "\n"
            if condition.type == "InstallPlanPending" and condition.status == "True" then
              numPending = numPending + 1
            elseif (condition.type == "InstallPlanMissing" and condition.reason ~= "ReferencedInstallPlanNotFound") then
              numDegraded = numDegraded + 1
            elseif (condition.type == "CatalogSourcesUnhealthy" or condition.type == "InstallPlanFailed") and condition.status == "True" then
              numDegraded = numDegraded + 1
            end
          end
          if numDegraded == 0 and numPending == 0 then
            health_status.status = "Healthy"
            health_status.message = msg
            return health_status
          elseif numPending > 0 and numDegraded == 0 then
            health_status.status = "Progressing"
            health_status.message = "An install plan for a subscription is pending installation"
            return health_status
          else
            health_status.status = "Degraded"
            health_status.message = msg
            return health_status
          end
        end
      end
      health_status.status = "Progressing"
      health_status.message = "An install plan for a subscription is pending installation"
      return health_status

  monitoring.coreos.com/Prometheus:
    health.lua: |
      local hs={ status = "Progressing", message = "Waiting for initialization" }
      found_status = false

      if obj.status ~= nil then
        found_status = true
        if obj.status.conditions ~= nil then
          for i, condition in ipairs(obj.status.conditions) do

            if condition.type == "Available" and condition.status ~= "True" then
              if condition.reason == "SomePodsNotReady" then
                hs.status = "Progressing"
              else
                hs.status = "Degraded"
              end
              hs.message = condition.message or condition.reason
            end
            if condition.type == "Available" and condition.status == "True" then
              hs.status = "Healthy"
              hs.message = "All instances are available"
            end
          end
        end
      end

      if not found_status then
          hs = { status = "Healthy", message = "All instances are available" }
      end

      return hs

# ------------------------------------------------
# OpenShift Gitops Setup
# ------------------------------------------------

ocp4_workload_connectivity_link_argocd_manager_service_account: argocd-manager
ocp4_workload_connectivity_link_argocd_namespace: openshift-gitops

ocp4_workload_connectivity_link_argocd_local_cluster: local

ocp4_workload_connectivity_link_argocd_repo_secret: cl-repo

ocp4_workload_connectivity_link_gitops_repo: https://github.com/rh-soln-pattern-connectivity-link/cl-install-helm.git

ocp4_workload_connectivity_link_gitops_infra_project: infra

# ------------------------------------------------
# Kuadrant Operator
# ------------------------------------------------

ocp4_workload_connectivity_link_kuadrant_operator_application_name: kuadrant-operator
ocp4_workload_connectivity_link_kuadrant_operator_application_namespace: kuadrant-system
ocp4_workload_connectivity_link_kuadrant_operator_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_kuadrant_operator_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_kuadrant_operator_gitops_repo_path: platform/kuadrant-operator

ocp4_workload_connectivity_link_kuadrant_operator_operator_channel: stable
ocp4_workload_connectivity_link_kuadrant_operator_operator_install_plan_approval: Automatic
ocp4_workload_connectivity_link_kuadrant_operator_operator_starting_csv: ""
ocp4_workload_connectivity_link_kuadrant_operator_operator_name: kuadrant-operator
ocp4_workload_connectivity_link_kuadrant_operator_catalogsource_image: quay.io/kuadrant/kuadrant-operator-catalog:v0.11.0

# ------------------------------------------------
# Kuadrant
# ------------------------------------------------

ocp4_workload_connectivity_link_kuadrant_applicationset_name: kuadrant
ocp4_workload_connectivity_link_kuadrant_application_name: kuadrant
ocp4_workload_connectivity_link_kuadrant_application_namespace: kuadrant-system
ocp4_workload_connectivity_link_kuadrant_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_kuadrant_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_kuadrant_gitops_repo_path: platform/kuadrant

# ------------------------------------------------
# Sail Operator
# ------------------------------------------------

ocp4_workload_connectivity_link_servicemesh_operator_application_name: servicemesh-operator
ocp4_workload_connectivity_link_servicemesh_operator_application_namespace: gateway-system
ocp4_workload_connectivity_link_servicemesh_operator_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_servicemesh_operator_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_servicemesh_operator_gitops_repo_path: platform/sail-operator

ocp4_workload_connectivity_link_servicemesh_operator_operator_channel: 
ocp4_workload_connectivity_link_servicemesh_operator_operator_install_plan_approval: Automatic
ocp4_workload_connectivity_link_servicemesh_operator_operator_starting_csv: ""
ocp4_workload_connectivity_link_servicemesh_operator_operator_name: servicemeshoperator3
ocp4_workload_connectivity_link_servicemesh_operator_catalogsource: redhat-operators
ocp4_workload_connectivity_link_servicemesh_operator_catalogsource_namespace: openshift-marketplace

# ------------------------------------------------
# Istio
# ------------------------------------------------

ocp4_workload_connectivity_link_istio_application_name: istio
ocp4_workload_connectivity_link_istio_application_namespace: istio-system
ocp4_workload_connectivity_link_istio_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_istio_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_istio_gitops_repo_path: platform/istio

# ------------------------------------------------
# Ingress Gateway
# ------------------------------------------------

ocp4_workload_connectivity_link_ingress_gateway_application_name: ingress-gateway
ocp4_workload_connectivity_link_ingress_gateway_application_namespace: ingress-gateway
ocp4_workload_connectivity_link_ingress_gateway_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_ingress_gateway_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_ingress_gateway_gitops_repo_path: platform/ingress-gateway
ocp4_workload_connectivity_link_ingress_gateway_name: prod-web

ocp4_workload_connectivity_link_ingress_gateway_tls_issuer_private_key_secret: le-production
ocp4_workload_connectivity_link_ingress_gateway_tls_issuer_server: https://acme-v02.api.letsencrypt.org/directory
ocp4_workload_connectivity_link_ingress_gateway_routing_strategy: loadbalanced

# ------------------------------------------------
# Observability Hub
# ------------------------------------------------

ocp4_workload_connectivity_link_observability_hub_application_name: observability-hub
ocp4_workload_connectivity_link_observability_hub_application_namespace: monitoring
ocp4_workload_connectivity_link_observability_hub_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_observability_hub_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_observability_hub_gitops_repo_path: platform/observability-hub

# ------------------------------------------------
# Observability Worker
# ------------------------------------------------

ocp4_workload_connectivity_link_observability_worker_application_name: observability-worker
ocp4_workload_connectivity_link_observability_worker_application_namespace: monitoring
ocp4_workload_connectivity_link_observability_worker_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_observability_worker_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_observability_worker_gitops_repo_path: platform/observability-worker

# ------------------------------------------------
# RHSSO Operator
# ------------------------------------------------

ocp4_workload_connectivity_link_rhsso_operator_application_name: rhsso-operator
ocp4_workload_connectivity_link_rhsso_operator_application_namespace: rhsso
ocp4_workload_connectivity_link_rhsso_operator_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_rhsso_operator_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_rhsso_operator_gitops_repo_path: platform/rhsso-operator

ocp4_workload_connectivity_link_rhsso_operator_operator_channel: stable
ocp4_workload_connectivity_link_rhsso_operator_operator_install_plan_approval: Automatic
ocp4_workload_connectivity_link_rhsso_operator_operator_starting_csv: rhsso-operator.7.6.5-opr-004
ocp4_workload_connectivity_link_rhsso_operator_operator_name: rhsso-operator
ocp4_workload_connectivity_link_rhsso_operator_catalogsource: redhat-operators
ocp4_workload_connectivity_link_rhsso_operator_catalogsource_namespace: openshift-marketplace

# ------------------------------------------------
# RHSSO
# ------------------------------------------------

ocp4_workload_connectivity_link_rhsso_application_name: rhsso
ocp4_workload_connectivity_link_rhsso_application_namespace: rhsso
ocp4_workload_connectivity_link_rhsso_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_rhsso_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_rhsso_gitops_repo_path: platform/rhsso

ocp4_workload_connectivity_link_rhsso_keycloak_name: keycloak
ocp4_workload_connectivity_link_rhsso_apicurio_realm: apicurio

# ------------------------------------------------
# Apicurio Studio Operator
# ------------------------------------------------

ocp4_workload_connectivity_link_apicurio_studio_operator_application_name: apicurio-studio-operator
ocp4_workload_connectivity_link_apicurio_studio_operator_application_namespace: apicurio
ocp4_workload_connectivity_link_apicurio_studio_operator_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_apicurio_studio_operator_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_apicurio_studio_operator_gitops_repo_path: platform/apicurio-studio-operator

# ------------------------------------------------
# Apicurio Studio
# ------------------------------------------------

ocp4_workload_connectivity_link_apicurio_studio_application_name: apicurio-studio
ocp4_workload_connectivity_link_apicurio_studio_application_namespace: apicurio
ocp4_workload_connectivity_link_apicurio_studio_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_apicurio_studio_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_apicurio_studio_gitops_repo_path: platform/apicurio-studio

ocp4_workload_connectivity_link_apicurio_studio_name: apicurio-studio

# ------------------------------------------------
# Echo Api test app
# ------------------------------------------------

ocp4_workload_connectivity_link_echo_api_application_name: echo-api
ocp4_workload_connectivity_link_echo_api_application_namespace: echo-api
ocp4_workload_connectivity_link_echo_api_gitops_repo: "{{ ocp4_workload_connectivity_link_gitops_repo }}"
ocp4_workload_connectivity_link_echo_api_gitops_repo_tag: v0.11.0
ocp4_workload_connectivity_link_echo_api_gitops_repo_path: developer/echo-api

ocp4_workload_connectivity_link_echo_api_http_route_host: echo


ocp4_workload_connectivity_link_monitoring_hub: true

# ------------------------------------------------
# Web Terminal Operator
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_webterminal_operator_channel: "fast"
ocp4_workload_cloud_architecture_workshop_webterminal_operator_automatic_install_plan_approval: true
ocp4_workload_cloud_architecture_workshop_webterminal_operator_starting_csv: ""
ocp4_workload_cloud_architecture_workshop_webterminal_operator_wait_for_deploy: true
ocp4_workload_cloud_architecture_workshop_webterminal_operator_name: web-terminal
ocp4_workload_cloud_architecture_workshop_webterminal_operator_csv_prefix: web-terminal
ocp4_workload_cloud_architecture_workshop_webterminal_operator_catalog_source: redhat-operators
ocp4_workload_cloud_architecture_workshop_webterminal_operator_deployment: web-terminal-controller
ocp4_workload_cloud_architecture_workshop_webterminal_operator_namespace: openshift-operators
ocp4_workload_cloud_architecture_workshop_webterminal_operator_use_catalog_snapshot: false
ocp4_workload_cloud_architecture_workshop_webterminal_operator_catalogsource_name: ""
ocp4_workload_cloud_architecture_workshop_webterminal_operator_catalogsource_namespace: openshift-operators
ocp4_workload_cloud_architecture_workshop_webterminal_operator_catalog_snapshot_image: ""
ocp4_workload_cloud_architecture_workshop_webterminal_operator_catalog_snapshot_image_tag: ""