---

- name: Install RHSSO operator
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'rhsso_operator_applicationset.yaml.j2') | from_yaml }}"

- name: Install RHSSO
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'rhsso_applicationset.yaml.j2') | from_yaml }}"
