---

- name: User workload monitoring
  ansible.builtin.include_tasks: user_workload_monitoring.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Setup OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops_setup.yml

- name: Install Kuadrant
  ansible.builtin.include_tasks: kuadrant.yml

- name: Install Sail operator and Istio
  ansible.builtin.include_tasks: istio.yml

- name: Install Ingress gateway
  ansible.builtin.include_tasks: ingress_gateway.yml

- name: Install Observability
  ansible.builtin.include_tasks: observability.yaml

- name: Install RHSSO
  ansible.builtin.include_tasks: rhsso.yml

- name: Install Apicurio Studio
  ansible.builtin.include_tasks: apicurio_studio.yml
